computeType: AKS
autoScaler:
  autoscaleEnabled: True
  minReplicas: 1
  maxReplicas: 3
  refreshPeriodInSeconds: 10
  targetUtilization: 70
authEnabled: True
containerResourceRequirements:
  cpu: 1
  memoryInGB: 0.5
appInsightsEnabled: True
scoringTimeoutMs: 1000
maxConcurrentRequestsPerContainer: 2
maxQueueWaitMs: 1000
sslEnabled: False
